version: "3.8"
services:
  todo_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql-net

  db-mysql:
    image: mysql:5.7.34
    ports:
      - "3307:3307"
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - env/mysql.env
    networks:
      - springboot-mysql-net
  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
networks:
  springboot-mysql-net:
    driver: bridge