version: "3.8"
services:
  todo_app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - env/app.env
    depends_on:
      - db-mysql
    ports:
      - "8080:8080"
  db-mysql:
    image: mysql:5.7.34
    ports:
      - "3307:3307"
    env_file:
      - env/mysql.env
  nginx:
    image: nginx:1.19.10
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - todo_app
  redis:
    image: redis:6.2.5
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf